# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

  sokoban00:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: sokoban00 trial (logging = false)
      working-directory: ./test/trials_no_logging/
      run: |
        python -m unittest sokoban00.py

  sokoban01:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: sokoban01 trial (logging = false)
      working-directory: ./test/trials_no_logging/
      run: |
        python -m unittest sokoban01.py

  sokoban02:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: sokoban02 trial (logging = false)
      working-directory: ./test/trials_no_logging/
      run: |
        python -m unittest sokoban02.py

  sokoban03:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: sokoban03 trial (logging = false)
      working-directory: ./test/trials_no_logging/
      run: |
        python -m unittest sokoban03.py

  sokoban04:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: sokoban04 trial (logging = false)
      working-directory: ./test/trials_no_logging/
      run: |
        python -m unittest sokoban04.py

  sokoban05a:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: sokoban05a trial (logging = false)
      working-directory: ./test/trials_no_logging/
      run: |
        python -m unittest sokoban05a.py

  sokoban05b:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: sokoban05b trial (logging = false)
      working-directory: ./test/trials_no_logging/
      run: |
        python -m unittest sokoban05b.py

  sokoban06a:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: sokoban06a trial (logging = false)
      working-directory: ./test/trials_no_logging/
      run: |
        python -m unittest sokoban06a.py

  sokoban06b:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: sokoban06b trial (logging = false)
      working-directory: ./test/trials_no_logging/
      run: |
        python -m unittest sokoban06b.py

  sokoban06c:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: sokoban06c trial (logging = false)
      working-directory: ./test/trials_no_logging/
      run: |
        python -m unittest sokoban06c.py

  sokoban07a:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: sokoban07a trial (logging = false)
      working-directory: ./test/trials_no_logging/
      run: |
        python -m unittest sokoban07a.py

  sokoban07b:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: sokoban07b trial (logging = false)
      working-directory: ./test/trials_no_logging/
      run: |
        python -m unittest sokoban07b.py

  sokoban08:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: sokoban08 trial (logging = false)
      working-directory: ./test/trials_no_logging/
      run: |
        python -m unittest sokoban08.py

  sokoban09:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: sokoban09 trial (logging = false)
      working-directory: ./test/trials_no_logging/
      run: |
        python -m unittest sokoban09.py

  sokoban10:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: sokoban10 trial (logging = false)
      working-directory: ./test/trials_no_logging/
      run: |
        python -m unittest sokoban10.py

    # Trials WITH full logging:

#    - name: sokoban00 trial (logging = true)
#      working-directory: ./test/trials_with_logging/
#      run: |
#        python sokoban00.py
#
#    - name: sokoban01 trial (logging = true)
#      working-directory: ./test/trials_with_logging/
#      run: |
#        python sokoban01.py
#
#    - name: sokoban02 trial (logging = true)
#      working-directory: ./test/trials_with_logging/
#      run: |
#        python sokoban02.py
#
#    - name: sokoban03 trial (logging = true)
#      working-directory: ./test/trials_with_logging/
#      run: |
#        python sokoban03.py
#
#    - name: sokoban04 trial (logging = true)
#      working-directory: ./test/trials_with_logging/
#      run: |
#        python sokoban04.py
#
#    - name: sokoban05a trial (logging = true)
#      working-directory: ./test/trials_with_logging/
#      run: |
#        python sokoban05a.py
#
#    - name: sokoban05b trial (logging = true)
#      working-directory: ./test/trials_with_logging/
#      run: |
#        python sokoban05b.py
#
#    - name: sokoban06a trial (logging = true)
#      working-directory: ./test/trials_with_logging/
#      run: |
#        python sokoban06a.py
#
#    - name: sokoban06b trial (logging = true)
#      working-directory: ./test/trials_with_logging/
#      run: |
#        python sokoban06b.py
#
#    - name: sokoban06c trial (logging = true)
#      working-directory: ./test/trials_with_logging/
#      run: |
#        python sokoban06c.py
#
#    - name: sokoban07a trial (logging = true)
#      working-directory: ./test/trials_with_logging/
#      run: |
#        python sokoban07a.py
#
#    - name: sokoban07b trial (logging = true)
#      working-directory: ./test/trials_with_logging/
#      run: |
#        python sokoban07b.py
#
#    - name: sokoban08 trial (logging = true)
#      working-directory: ./test/trials_with_logging/
#      run: |
#        python sokoban08.py
#
#    - name: sokoban09 trial (logging = true)
#      working-directory: ./test/trials_with_logging/
#      run: |
#        python sokoban09.py
#
#    - name: sokoban10 trial (logging = true)
#      working-directory: ./test/trials_with_logging/
#      run: |
#        python sokoban10.py
